apiVersion: v1
kind: Service
metadata:
  name: ai-service
  labels:
    app: ai-service
    monitoring: enabled
spec:
  type: ClusterIP
  selector:
    app: ai-service
  ports:
    - name: http
      port: 8084
      targetPort: 8084
    - name: grpc
      port: 9084
      targetPort: 9084
