// Tests encodeToWav's resample -> PCM16 -> WAV-header pipeline against a mocked
// Web Audio API (jsdom implements neither AudioContext nor webkitAudioContext).
import { encodeToWav } from './wavEncoder';

const fakeBlob = () => ({ arrayBuffer: async () => new ArrayBuffer(8) });

const buildFakeAudioBuffer = (overrides = {}) => ({
  numberOfChannels: 1,
  sampleRate: 16000,
  length: 4,
  getChannelData: () => new Float32Array([0.5, -0.5, 1, -1]),
  ...overrides,
});

const blobToArrayBuffer = (blob) => (blob.arrayBuffer
  ? blob.arrayBuffer()
  : new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onload = () => resolve(reader.result);
    reader.onerror = reject;
    reader.readAsArrayBuffer(blob);
  }));

/**
 * Unpacks a PCM16 WAV blob generated by encodeToWav into its header fields
 * and signed 16-bit PCM samples for rigorous byte-content assertion.
 */
const unpackWav = async (blob) => {
  const buffer = await blobToArrayBuffer(blob);
  const view = new DataView(buffer);
  const getAscii = (offset, length) => Array.from({ length }, (_, i) => String.fromCharCode(view.getUint8(offset + i))).join('');

  return {
    riff: getAscii(0, 4),
    fileSize: view.getUint32(4, true),
    wave: getAscii(8, 4),
    fmt: getAscii(12, 4),
    audioFormat: view.getUint16(20, true),
    numChannels: view.getUint16(22, true),
    sampleRate: view.getUint32(24, true),
    bitsPerSample: view.getUint16(34, true),
    dataTag: getAscii(36, 4),
    dataSize: view.getUint32(40, true),
    samples: Array.from(new Int16Array(buffer, 44, (buffer.byteLength - 44) / 2)),
  };
};

describe('encodeToWav', () => {
  let decodeAudioDataMock;
  let closeMock;

  beforeEach(() => {
    decodeAudioDataMock = jest.fn();
    closeMock = jest.fn().mockResolvedValue(undefined);
    window.AudioContext = jest.fn().mockImplementation(() => ({
      decodeAudioData: decodeAudioDataMock,
      close: closeMock,
    }));
  });

  afterEach(() => {
    delete window.AudioContext;
    delete window.webkitAudioContext;
  });

  it('produces a 44-byte-header WAV blob with accurate PCM16 samples when already at the 16kHz target rate', async () => {
    decodeAudioDataMock.mockResolvedValue(buildFakeAudioBuffer());

    const blob = await encodeToWav(fakeBlob());

    expect(blob.type).toBe('audio/wav');
    expect(blob.size).toBe(44 + 4 * 2); // header + 4 PCM16 samples

    const wav = await unpackWav(blob);
    expect(wav.riff).toBe('RIFF');
    expect(wav.wave).toBe('WAVE');
    expect(wav.fmt).toBe('fmt ');
    expect(wav.audioFormat).toBe(1); // PCM
    expect(wav.numChannels).toBe(1); // Mono
    expect(wav.sampleRate).toBe(16000);
    expect(wav.bitsPerSample).toBe(16);
    expect(wav.dataTag).toBe('data');
    expect(wav.dataSize).toBe(8); // 4 samples * 2 bytes
    // Float32 [0.5, -0.5, 1, -1] -> PCM16 [16383, -16384, 32767, -32768]
    expect(wav.samples).toEqual([16383, -16384, 32767, -32768]);
    expect(closeMock).toHaveBeenCalledTimes(1);
  });

  it('downmixes multiple channels before encoding', async () => {
    decodeAudioDataMock.mockResolvedValue(buildFakeAudioBuffer({
      numberOfChannels: 2,
      getChannelData: (channel) => (channel === 0
        ? new Float32Array([1, 1, 1, 1])
        : new Float32Array([-1, -1, -1, -1])),
    }));

    const blob = await encodeToWav(fakeBlob());

    // Averaging +1 and -1 across channels yields silence (all zeroes).
    expect(blob.size).toBe(44 + 4 * 2);
    const wav = await unpackWav(blob);
    expect(wav.numChannels).toBe(1);
    expect(wav.samples).toEqual([0, 0, 0, 0]);
  });

  it('linearly resamples when the source sample rate is not 16kHz', async () => {
    decodeAudioDataMock.mockResolvedValue(buildFakeAudioBuffer({
      sampleRate: 32000,
      length: 8,
      getChannelData: () => new Float32Array(8).fill(0.25),
    }));

    const blob = await encodeToWav(fakeBlob());

    // ratio = 32000/16000 = 2 -> outLength = round(8/2) = 4 samples.
    expect(blob.size).toBe(44 + 4 * 2);
    const wav = await unpackWav(blob);
    expect(wav.sampleRate).toBe(16000);
    expect(wav.samples).toEqual([8191, 8191, 8191, 8191]);
  });

  it('clamps out-of-range samples to the int16 boundary instead of overflowing', async () => {
    decodeAudioDataMock.mockResolvedValue(buildFakeAudioBuffer({
      length: 2,
      getChannelData: () => new Float32Array([5, -5]),
    }));

    const blob = await encodeToWav(fakeBlob());

    expect(blob.size).toBe(44 + 2 * 2);
    const wav = await unpackWav(blob);
    expect(wav.samples).toEqual([32767, -32768]);
  });

  it('falls back to webkitAudioContext when AudioContext is unavailable', async () => {
    delete window.AudioContext;
    window.webkitAudioContext = jest.fn().mockImplementation(() => ({
      decodeAudioData: decodeAudioDataMock,
      close: closeMock,
    }));
    decodeAudioDataMock.mockResolvedValue(buildFakeAudioBuffer());

    const blob = await encodeToWav(fakeBlob());

    expect(blob.type).toBe('audio/wav');
  });

  it('still closes the audio context when decoding fails', async () => {
    decodeAudioDataMock.mockRejectedValue(new Error('bad audio'));

    await expect(encodeToWav(fakeBlob())).rejects.toThrow('bad audio');
    expect(closeMock).toHaveBeenCalledTimes(1);
  });
});
